# Single trial instructed task only.
trainer_type: parallel
random_seed: 42

tasks:
  - task_type: instructed
    eval: true
    weight: 1.0
    task:
      dt: 10.0
      input_noise_std: 0.05
      w_m: 0.05

model:
  input_size: 5
  hidden_size: 128
  output_size: 2
  tau: 100.0
  dt: 10.0
  activation: elu
  noise_std: 0.1

training:
  learning_rate: 3e-3
  batch_size: 64
  total_steps: 100
  log_interval: 20
  num_eval_samples: 32
  checkpoint_interval: 500
  log_dir: logs/test
  optimizer_type: adam
  clip_grad_norm: 1.0
